'''
Cross check block_assignment files
'''
import locale
import csv


def cross_check_baf(precinct_district_assignment_file, precinct_block_assignment_file, district_block_assignment_file):
    precinct_to_district_baf = dict()
    block_to_precinct_baf = dict()
    block_to_district_baf = dict()
    precinct_cnt = 0
    precinct_block_cnt = 0
    district_block_cnt = 0

    # PRECINCT,COM_DIST
    with open(precinct_district_assignment_file, 'r') as fp1:
        csvreader = csv.DictReader(fp1)
        for row in csvreader:
            precinct_to_district_baf[row['PRECINCT']] = row['COM_DIST']
            precinct_cnt += 1

    # BLOCK,PRECINCT
    with open(precinct_block_assignment_file, 'r') as fp2:
        csvreader = csv.DictReader(fp2)
        for row in csvreader:
            if row['PRECINCT'] not in precinct_to_district_baf:
                ValueError(f"Precinct BAF precinct is not in district BAF for {row['PRECINCT']=}")
            block_to_precinct_baf[row['BLOCK']] = row['PRECINCT']
            precinct_block_cnt += 1

    # BLOCK,DISTRICT
    with open(district_block_assignment_file, 'r') as fp2:
        csvreader = csv.DictReader(fp2)
        for row in csvreader:
            if row['BLOCK'] not in block_to_precinct_baf:
                ValueError(f"District BAF precinct is not in precinct BAF for {row['BLOCK']=}")
            block_to_district_baf[row['BLOCK']] = row['DISTRICT']
            district_block_cnt += 1

    if precinct_block_cnt != district_block_cnt:
        raise ValueError(f"Mismatched BAF counts: {precinct_block_cnt=} != {district_block_cnt=}")

    # At this point, the block assignment files seem good. Cross check the precinct and district values
    for block in block_to_precinct_baf.keys():
        district = block_to_district_baf[block]
        precinct = block_to_precinct_baf[block]
        district2 = precinct_to_district_baf[precinct]
        if district != district2:
            raise ValueError(f"Mismatch precinct and commissioner district by block number: {block=},{precinct=},{district=},{district2=}")

    print("Files check out OK!")


if __name__ == '__main__':
    locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')  # For parsing numbers with comma separators

    # epc_precincts_2022.csv was exported from QGIS for the attribute table for Precinct.zip shapefile
    # precinct_block_assign_file.csv was generated by create_epc_block_assignment_file.py
    # epc_commissioner_districts_2022.csv was exported by ESRI Redistricting from a manually generated map of the commissioner districts
    cross_check_baf('./epc_files/epc_precincts_2022.csv', './epc_files/precinct_block_assign_file.csv', './epc_files/epc_commissioner_districts_2022.csv')
